#! /bin/bash -eux

#
# General configuration
#

source globals

target_directory=$ECS_VOLUME_POOL_PATH
target_image_file="$ECS_CDROM_FILE_NAME"

tmpdir="${TMPDIR:-/tmp}"
downloads="${tmpdir}"

builddir="$tmpdir/build.$$"
mntdir="$tmpdir/mnt.$$"

#
# Ubuntu release selection
#
release_name="16.04.1"
release_version="16.04.1"
release_variant="server"
release_architecture="amd64"

release_base_url="http://releases.ubuntu.com"
release_base_name="ubuntu-$release_version-$release_variant-$release_architecture"
release_image_file="$release_base_name.iso"
release_url="$release_base_url/$release_name/$release_image_file"

#
# Network settings
#
network_iface='eth0'
network_ip='10.20.0.20'
network_gateway='10.20.0.1'

progress() {
    echo "$*" >&2
}

error() {
    code="$1"; shift
    echo "ERROR: $*" >&2
    exit $code
}

create_directory() {
    path="$1"
    if [ ! -d "$path" ]; then
      progress "Creating directory $path..."
      mkdir -p "$path" || error 2 "Failed to create directory $path"
    fi
}

extract_iso() {
    archive="$1"
    if [ ! -r "$archive" ]; then
    error 1 "Cannot read ISO image $archive."
    fi
    directory="$2"
    if [ ! -d "$directory" ]; then
    mkdir "$directory" || exit 2 "Cannot extract CD to $directory"
    fi

    progress "Mounting image $archive (you may be asked for your password to authorize)..."
    create_directory "$mntdir"
    mount -r -o loop "$archive" "$mntdir" || error 2 "Failed to mount image $archive"

    progress "Copying image contents..."
    cp -rT "$mntdir" "$directory" || error 2 "Failed to copy content of image $archive to $directory"
    chmod -R u+w "$directory"

    progress "Unmounting image $archive from $mntdir..."
    umount "$mntdir"
    rmdir "$mntdir"
}

preset_language() {
    progress "Presetting language to 'en'..."
    echo "en" >"isolinux/lang" || error 2 "Failed to write $(pwd)/isolinux/lang"
}

create_kscfg() {
    if [ ! -f "ks.cfg" ]; then
    progress "Create ks.cfg file..."
    cat >"ks.cfg" <<EOF
#Generated by Kickstart Configurator
#platform=AMD64 or Intel EM64T

#System language
lang en_US
#Language modules to install
langsupport en_US
#System keyboard
keyboard gb_mac_intl
#System mouse
mouse
#System timezone
timezone --utc Europe/Moscow
#Root password
rootpw --disabled
#Initial user
user test --fullname "test" --password qwe123QWE
#Reboot after installation
reboot
#Use text mode install
text
#Install OS instead of upgrade
install
#Use CDROM installation media
cdrom
#System bootloader configuration
bootloader --location=mbr 
#Clear the Master Boot Record
zerombr yes
#Partition clearing information
clearpart --all --initlabel 
#Disk partitioning information
part / --fstype ext4 --size 1 --grow 
part swap --recommended 
#System authorization infomation
auth  --useshadow  --enablemd5 
#Network information
#network --bootproto=dhcp --device=eth0
network --bootproto=static --ip=${network_ip} --netmask=255.255.255.0 --gateway=${network_gateway} --nameserver=8.8.8.8 --device=${network_iface}
#Firewall configuration
firewall --disabled 
#Do not configure the X Window System
skipx
%packages
@ ubuntu-server
openssh-server
%post --nochroot 
echo done
EOF
    fi
}

create_kspreseed() {
    if [ ! -f "ks.preseed" ]; then
    progress "Create ks.preseed file..."
    cat >"ks.preseed" <<EOF
d-i partman/confirm_write_new_label boolean true
d-i partman/choose_partition \
select Finish partitioning and write changes to disk
d-i partman/confirm boolean true
EOF
    fi
}

patch_txtcfg() {
    (cd "isolinux" && cp txt.cfg /root/ecs/txt.cfg;
    patch -p0 <<EOF
--- txt.cfg     2016-08-18 13:49:11.316359931 +0200
+++ txt.cfg.orig  2016-08-18 13:45:20.889321343 +0200
@@ -2,7 +2,7 @@
 label install
   menu label ^Install Ubuntu Server
   kernel /install/vmlinuz
-  append  file=/cdrom/preseed/ubuntu-server.seed vga=788 initrd=/install/initrd.gz quiet ---
+  append  file=/cdrom/preseed/ubuntu-server.seed initrd=/install/initrd.gz ks=cdrom:/ks.cfg preseed/file=/cdrom/ks.preseed quiet ---
 label maas
   menu label ^Install MAAS Region Controller
   kernel /install/vmlinuz
EOF
    )
}

patch_isolinuxcfg() {
    (cd "isolinux";
    patch -p0 <<EOF
*** isolinux.cfg.orig    2013-05-14 10:20:37.000000000 +0200
--- isolinux.cfg    2013-05-14 10:20:50.000000000 +0200
***************
*** 2,6 ****
  include menu.cfg
  default vesamenu.c32
  prompt 0
! timeout 0
  ui gfxboot bootlogo
--- 2,6 ----
  include menu.cfg
  default vesamenu.c32
  prompt 0
! timeout 5
  ui gfxboot bootlogo
EOF
    )
}

modify_release() {
    preset_language && \
    create_kscfg && \
    create_kspreseed && \
    patch_txtcfg && \
    patch_isolinuxcfg 
}

create_image() {
    local force=${1:-''}
    local target_file=$target_directory/$target_image_file
    local source_file="$downloads/$release_image_file"

    if [ -n "$force" ] ; then
      rm -f "$target_file"
    fi

    if [ -f "$target_file" ] ; then
      echo "INFO: target image file is already created"
      return 0
    fi

    if [ ! -f "$source_file" ]; then
      create_directory "$downloads"
      progress "Downloading Ubuntu $release_name $release_variant..."
      if ! wget "$release_url" -P "$downloads" ; then
        echo ERROR: failed to download iso image
        return 1
      fi
    fi

    create_directory "$builddir"
    extract_iso "$source_file" "$builddir"
    pushd "$builddir"
    if ! modify_release ; then
      popd
      echo ERROR: failed to modify iso image
      return 1
    fi
    popd

    create_directory "$target_directory"
    progress "Creating ISO image $target_image_file..."
    if ! mkisofs -D -r -V "UNATTENDED_UBUNTU" -cache-inodes -J -l \
        -b isolinux/isolinux.bin \
        -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 \
        -boot-info-table \
        -o "$target_file" \
        "$builddir" ; then
      echo ERROR: failed to make iso
      return 1
    fi

    if [ "x$builddir" != x -a "x$builddir" != "x/" ]; then
        rm -rf "$builddir"
    fi
}

create_image

